config/routes.rb
InteractiveTail::Application.routes.draw do
  resources :log_files
  resources :logs do
    collection do
      get :index_grouped_by_tags
    end
  end
end

app/models/log.rb
# -*- encoding: utf-8 -*-

class Log < ActiveRecord::Base
  attr_accessible :contents, :location, :time, :time_in_log

  default_scope :order => 'time'
  paginates_per 100

  belongs_to :log_file

  before_save :set_time

  def set_time
    self.time = Time.now
  end

  def tags
    self.contents.scan(/\[\[([^\]]+)\]\]/).flatten
  end

  def contents_after_tags
    self.contents[/\]\]\s*([^\]]*)$/, 1] || self.contents
  end

  # Read '(insert:foo/bar.txt:t01:15)' from contents
  # to insert 15 to t01-marked point at foo/bar.txt.
  def read_log_to_insert_to_file
    self.contents.scan(/\(insert:([^:]+):([^:]+):([^:]+)\)/).each do |fname, tag, val|
      Log.insert_string_to_file(fname, tag => val)
    end
  end
  after_save :read_log_to_insert_to_file

  def encode_contents
    self.contents = self.contents.encode(
      "UTF-8", "UTF-8", invalid: :replace, undef: :replace, replace: '.')
  end
  before_save :encode_contents

  # Example:
  #   run
  #     insert_string_to_file("foo/bar.txt", 't01' => 'abc')
  #   then
  #     arr.d('t01:').sort.uniq at file foo/bar.txt
  #   is convert to
  #     arr.d('t01:abc').sort.uniq
  def self.insert_string_to_file(target_fname, mark_value_pairs)
    raise "#{target_fname} is not found" unless File.exist?(target_fname)

    old_contents = File.read(target_fname)
    open(target_fname, 'w') do |f|
      mark_value_pairs.each do |mark, value|
        f.write old_contents.gsub(/\b#{mark}:/, "#{mark}:#{value}")
      end
    end
  end
end

app/models/log_file.rb
# -*- encoding: utf-8 -*-

class LogFile < ActiveRecord::Base
  attr_accessible :file_name, :log_type, :pos, :limit_of_skip

  has_many :logs

  def save_tails
    return unless File.exist?(self.file_name)

    fp = open(self.file_name, 'r')
    fp.seek(self.start_pos)

    while line = fp.gets
      Log.create(
        :contents => line,
        :location => nil,
        :time => Time.now,
        :time_in_log => nil
      )
    end
    self.update_attribute(:pos, fp.pos)
    fp.close
  end

  # self.pos or forwarded self.pos
  def start_pos
    log_size = File.size(self.file_name)

    if self.pos + self.limit_of_skip < log_size
      log_size - self.limit_of_skip
    else
      self.pos
    end
  end

  def self.save_tails
    LogFile.all.each(&:save_tails)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def set_display_option
    @display_option = params[:display_option] || {}
  end
  before_filter :set_display_option
end

app/controllers/log_files_controller.rb
class LogFilesController < ApplicationController
  # GET /log_files
  # GET /log_files.json
  def index
    @log_files = LogFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @log_files }
    end
  end

  # GET /log_files/1
  # GET /log_files/1.json
  def show
    @log_file = LogFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log_file }
    end
  end

  # GET /log_files/new
  # GET /log_files/new.json
  def new
    @log_file = LogFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log_file }
    end
  end

  # GET /log_files/1/edit
  def edit
    @log_file = LogFile.find(params[:id])
  end

  # POST /log_files
  # POST /log_files.json
  def create
    @log_file = LogFile.new(params[:log_file])

    respond_to do |format|
      if @log_file.save
        format.html { redirect_to @log_file, notice: 'Log file was successfully created.' }
        format.json { render json: @log_file, status: :created, location: @log_file }
      else
        format.html { render action: "new" }
        format.json { render json: @log_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /log_files/1
  # PUT /log_files/1.json
  def update
    @log_file = LogFile.find(params[:id])

    respond_to do |format|
      if @log_file.update_attributes(params[:log_file])
        format.html { redirect_to @log_file, notice: 'Log file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @log_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /log_files/1
  # DELETE /log_files/1.json
  def destroy
    @log_file = LogFile.find(params[:id])
    @log_file.destroy

    respond_to do |format|
      format.html { redirect_to log_files_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_filter :save_tails

  def index
    @logs = Log.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end

  def index_grouped_by_tags
    @logs_each_tag = Log.all.inject({}) do |h, log|
      log.tags.each do |tag|
        h[tag] ||= []
        h[tag] << log
      end
      h
    end
  end

  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end

  def save_tails
    LogFile.save_tails
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_files_helper.rb
module LogFilesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
<head>
  <title>InteractiveTail</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type='text/javascript'><%= yield :js_for_specific_view %></script>
  <style><%= yield :css_for_specific_view %></style>
</head>
<body>

<div class="container">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav pull-left">
          <a class="brand">Interactive Tail</a>
          <li class="divider-vertical"></li>
          <li><%= link_to 'Log files', log_files_path %></li>
          <li><%= link_to 'Logs', logs_path %></li>
          <li><%= link_to 'Logs grouped by tags', index_grouped_by_tags_logs_path %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span10">
      <%= yield %>
    </div>
    <div class="span2">
      <%= content_for?(:side_bar) ? yield(:side_bar) : '' %>
    </div>
  </div>

  <div id="footer">
    <%= content_for?(:footer) ? yield(:footer) : '' %>
  </div>
</div>

</body>
</html>

app/views/log_files/_form.html.erb
<%= form_for(@log_file) do |f| %>
  <% if @log_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log_file.errors.count, "error") %> prohibited this log_file from being saved:</h2>

      <ul>
      <% @log_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :log_type %><br />
    <%= f.text_field :log_type %>
  </div>
  <div class="field">
    <%= f.label :pos %><br />
    <%= f.number_field :pos %>
  </div>
  <div class="field">
    <%= f.label :limit_of_skip %><br />
    <%= f.number_field :limit_of_skip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/log_files/edit.html.erb
<h1>Editing log_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @log_file %> |
<%= link_to 'Back', log_files_path %>

app/views/log_files/index.html.erb
<h1>Listing log_files</h1>

<table class='table table-striped table-bordered table-hover'>
  <tr>
    <th>File name</th>
    <th>Type</th>
    <th>Pos</th>
    <th>Limit of skip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @log_files.each do |log_file| %>
  <tr>
    <td><%= log_file.file_name %></td>
    <td><%= log_file.log_type %></td>
    <td><%= log_file.pos %></td>
    <td><%= log_file.limit_of_skip %></td>
    <td><%= link_to 'Show', log_file %></td>
    <td><%= link_to 'Edit', edit_log_file_path(log_file) %></td>
    <td><%= link_to 'Destroy', log_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Log file', new_log_file_path %>

app/views/log_files/new.html.erb
<h1>New log_file</h1>

<%= render 'form' %>

<%= link_to 'Back', log_files_path %>

app/views/log_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File name:</b>
  <%= @log_file.file_name %>
</p>

<p>
  <b>Type:</b>
  <%= @log_file.log_type %>
</p>

<p>
  <b>Pos:</b>
  <%= @log_file.pos %>
</p>

<p>
  <b>Limit of skip:</b>
  <%= @log_file.limit_of_skip %>
</p>


<%= link_to 'Edit', edit_log_file_path(@log_file) %> |
<%= link_to 'Back', log_files_path %>

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contents %><br />
    <%= f.text_field :contents %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :time_in_log %><br />
    <%= f.datetime_select :time_in_log %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<h1>Listing logs</h1>

<table class='table table-striped table-bordered table-hover'>
  <tr>
    <th>Contents</th>
    <th>Time</th>
    <th></th>
  </tr>

<% @logs.each do |log| %>
  <tr>
    <td><%= log.contents %></td>
    <td><%= log.time %></td>
    <td><%= link_to 'Show', log %></td>
  </tr>
<% end %>
</table>

<%= paginate @logs %>

<br />

app/views/logs/index_grouped_by_tags.html.erb
<% content_for :js_for_specific_view do %>
$(function(){
  $('table#logs').bind('reflect_to_table', function(){
    $.each(['width', 'height'], function(i, name){
      var val = $('#display_option_cell_' + name).val();
      $('table#logs tr td').css(name, val);
    });

    $('table#logs tr td').each(function(){
      var regexp = $('#display_option_cell_regexp').val();
      if(regexp == ''){
        regexp = '.*';
      }
      $('.expose', this).text($('.original', this).text().match(regexp));
    });

    $('table tr').each(function(){
      var regexp = $('#display_option_tag_regexp').val();
      if(regexp == ''){
        regexp = '.*';
      }

      $('table#logs tr').each(function(){
        if((new RegExp(regexp)).test($('.tag', this).text())){
          $(this).show();
        }else{
          $(this).hide();
        }
      });
    });

    return false;
  });

  $('form#display_options input').change(function(){
    $('#logs').trigger('reflect_to_table');
  });

  $('#logs').trigger('reflect_to_table');
});
<% end %>

<% content_for :css_for_specific_view do %>
table tr td .original { display: none; }
<% end %>

<h1>Listing logs</h1>

<%= form_tag "/logs/index_grouped_by_tags", method: 'get', class: 'form-horizontal', id: 'display_options' do %>
  <div class="control-group">
    <label class="control-label" for="cellWidth">Cell width</label>
    <div class="controls"><%= text_field_tag "display_option[cell_width]", @display_option[:cell_width], placeholder: "number" %></div>
  </div>
  <div class="control-group">
    <label class="control-label" for="cellHeight">Cell height</label>
    <div class="controls"><%= text_field_tag "display_option[cell_height]", @display_option[:cell_height], placeholder: "number" %></div>
  </div>
  <div class="control-group">
    <label class="control-label" for="tagRegexp">Cell filter</label>
    <div class="controls"><%= text_field_tag "display_option[cell_regexp]", @display_option[:cell_regexp], placeholder: "regular expression" %></div>
  </div>
  <div class="control-group">
    <label class="control-label" for="cellRegexp">Tag filter</label>
    <div class="controls"><%= text_field_tag "display_option[tag_regexp]", @display_option[:tag_regexp], placeholder: "regular expression" %></div>
  </div>
<% end %>

<table id='logs' class='table table-striped table-bordered table-hover'>
<% @logs_each_tag.each do |tag, logs| %>
  <tr>
  <td class='tag'>[[<%= tag %>]]</td>
  <% logs.each do |log| %>
      <td>
        <span class='original'><%= log.contents_after_tags %></span>
        <span class='expose'></span>
      </td>
  <% end %>
  </tr>
<% end %>
</table>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contents:</b>
  <%= @log.contents %>
</p>

<p>
  <b>Location:</b>
  <%= @log.location %>
</p>

<p>
  <b>Time:</b>
  <%= @log.time %>
</p>

<p>
  <b>Time in log:</b>
  <%= @log.time_in_log %>
</p>

<%= link_to 'Back', logs_path %>